-- MySQL Script generated by MySQL Workbench
-- 07/03/17 20:02:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trans
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trans
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trans` DEFAULT CHARACTER SET utf8 ;
USE `trans` ;

-- -----------------------------------------------------
-- Table `trans`.`uf_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`uf_cidade` (
  `cidade_id` INT(11) NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`cidade_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5571
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trans`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`veiculo` (
  `veiculo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NULL DEFAULT NULL,
  `nro_renavam` VARCHAR(20) NULL DEFAULT NULL,
  `ano` VARCHAR(9) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `chassi` VARCHAR(25) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `cor` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`veiculo_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COMMENT = '			';


-- -----------------------------------------------------
-- Table `trans`.`frete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`frete` (
  `frete_id` INT(11) NOT NULL AUTO_INCREMENT,
  `veiculo_id` INT(11) NOT NULL,
  `cidade_id` INT(11) NULL DEFAULT NULL,
  `data_entrada` DATE NULL DEFAULT NULL,
  `data_fechamento` DATE NULL DEFAULT NULL,
  `nro_entrada` INT(11) NULL DEFAULT NULL,
  `km_inicial` DOUBLE NULL DEFAULT NULL,
  `km_final` DOUBLE NULL DEFAULT '0',
  `km_percorrido` DOUBLE NULL DEFAULT '0',
  `vlr_frete` DOUBLE NULL DEFAULT NULL,
  `nf` VARCHAR(10) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `modificacao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`frete_id`),
  INDEX `frete_uf_cidade_idx` (`cidade_id` ASC),
  INDEX `frete_veiculo_idx` (`veiculo_id` ASC),
  CONSTRAINT `frete_uf_cidade_fk`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `trans`.`uf_cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `frete_veiculo_fk`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `trans`.`veiculo` (`veiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trans`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`motorista` (
  `motorista_id` INT(11) NOT NULL AUTO_INCREMENT,
  `veiculo_id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `nro_cnh` VARCHAR(15) NULL DEFAULT NULL,
  `tipo_cnh` VARCHAR(5) NULL DEFAULT NULL,
  `logradouro` VARCHAR(150) NULL DEFAULT NULL,
  `nro` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(150) NULL DEFAULT NULL,
  `bairro` VARCHAR(150) NULL DEFAULT NULL,
  `cep` VARCHAR(12) NULL DEFAULT NULL,
  `cidade_id` INT(11) NOT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`motorista_id`),
  INDEX `motorista_veiculo_idx` (`veiculo_id` ASC),
  INDEX `motorista_uf_cidade_idx` (`cidade_id` ASC),
  CONSTRAINT `motorista_uf_cidade_fk`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `trans`.`uf_cidade` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `motorista_veiculo_fk`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `trans`.`veiculo` (`veiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trans`.`pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`pagina` (
  `pagina_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pagina_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trans`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`usuario` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trans`.`usuario_pagina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trans`.`usuario_pagina` (
  `usuario_id` INT(11) NOT NULL,
  `pagina_id` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`, `pagina_id`),
  INDEX `usuario_pagina_idx` (`pagina_id` ASC),
  INDEX `pagina_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_pagina_pagina1`
    FOREIGN KEY (`pagina_id`)
    REFERENCES `trans`.`pagina` (`pagina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_pagina_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `trans`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
